name: Escalated Merge
# Merge actions kicked off by probot (https://github.com/SentientTechnologies/probot)
# This allows PRs from forked repos to run actions that require values from secrets when  a team member merges

on:
  repository_dispatch:
    types: [escalated-push-command]

jobs:
  tag:
    name: Tag Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '13'
      - name: Checkout Ref
        uses: actions/checkout@v1
        with:
          ref: ${{ github.event.client_payload.ref }}
      - name: Set Up Variables
        id: variables
        run: |
          export EMPTY_STRING=""
          echo ::set-output name=MAJOR::$(node -p "re = new RegExp('^(\\\d+).(\\\d+).(\\\d+)'); v = require('./package.json').version; re.exec(v)[1]")
          echo ::set-output name=MINOR::$(node -p "re = new RegExp('^(\\\d+).(\\\d+).(\\\d+)'); v = require('./package.json').version; re.exec(v)[2]")
        env:
          NPM_TOKEN: ""
      - name: Get github.ref
        run: echo ${{ github.ref }}
      - name: Get github.ref
        run: echo ${{ github.ref }}
      - name: Get github.event.ref
        run: echo ${{ github.event.ref }}
      - name: Get github.event.pull_request.ref
        run: echo ${{ github.event.pull_request.ref }}
      - name: Bump n Tag
        if: github.event.client_payload.ref == 'perm-testing'
        uses: evolv-ai/github-actions/semver-bump-tag@v4
        id: semver_bump
        with:
          token: "${{ github.token }}"
          major: ${{steps.variables.outputs.MAJOR}}
          minor: ${{steps.variables.outputs.MINOR}}
          bump: patch
          suffix: "test"
#      - name: Cherry Picker
#        if: github.event.client_payload.ref == 'perm-testing'
#        uses: evolv-ai/github-actions/cherry-picker@v6
#        id: cherry-picker
#        with:
#          token: "${{ secrets.GH_TOKEN }}"
#          pull_number: ${{ github.event.pull_request.number }}
#          slack_webhook: ${{ secrets.CHERRY_PICK_SLACK_WEBHOOK }}
