name: Cherry Pick Commits

on:
  pull_request:
    branches: 
      - perm-testing
    types: [closed]

jobs:
  tag:
    - name: Set Up Variables
      id: variables
      run: |
        export EMPTY_STRING=""
        echo ::set-output name=MAJOR::$(node -p "re = new RegExp('^(\\\d+).(\\\d+).(\\\d+)'); v = require('./package.json').version; re.exec(v)[1]")
        echo ::set-output name=MINOR::$(node -p "re = new RegExp('^(\\\d+).(\\\d+).(\\\d+)'); v = require('./package.json').version; re.exec(v)[2]")
      env:
        NPM_TOKEN: ""
        - name: Bump n Tag
          if: github.event.ref == 'refs/heads/master'
          uses: evolv-ai/github-actions/semver-bump-tag@v4
          id: semver_bump
          with:
            token: "${{ github.token }}"
            major: ${{steps.variables.outputs.MAJOR}}
            minor: ${{steps.variables.outputs.MINOR}}
            bump: patch
            suffix: ""
  cherry-pick:
    name: Cherry Pick Commits
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Cherry Picker
        uses: evolv-ai/github-actions/cherry-picker@v6
        id: cherry-picker
        with:
          token: "${{ secrets.GH_TOKEN }}"
          pull_number: ${{ github.event.pull_request.number }}
          slack_webhook: ${{ secrets.CHERRY_PICK_SLACK_WEBHOOK }}
