name: Run Tests and Linting

on:
  pull_request

jobs:
  deploy:
    name: Run Tests and Linting
    runs-on: ubuntu-latest
    steps:
      - name: Cherry Picker
        uses: evolv-ai/github-actions/cherry-picker@cherry-picker
        id: cherry-picker
        with:
          token: "${{ github.token }}"
          pull_request: "${{ github.event }}"
