on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    name: a job to release some code
    steps:
    - name: Hello world action step
      id: hello
      uses: evolv-ai/github-actions/release@master
      with:
        stage-to-release: 'staging'
        release-script: '/scripts/myman.sh'
