name: Deploy to Staging On Release Tag

on:
  push:
    tags:
      - 'release/*'

jobs:
  deploy:
    name: Deploy to Staging

    runs-on: ubuntu-latest

    steps:
      - name: Get the tag
        id: get_tag
        run: |
          echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
          echo ::set-output name=SEM_VER::${GITHUB_REF/refs\/tags\/release\/}
      - uses: actions/checkout@v1
        with: 
          ref: ${{ steps.get_tag.outputs.TAG }}
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: deploy-staging
          SLACK_TITLE: asset-manager deployment starting
          SLACK_MESSAGE: 'Deploying tag ${{ steps.get_tag.outputs.TAG }} to staging. https://github.com/evolv-ai/asset-manager/tree/${{ steps.get_tag.outputs.TAG }}'
          SLACK_COLOR: '#ffff00'
          SLACK_TITLE: Staging Deployment
          SLACK_USERNAME: deploy-bot
          SLACK_ICON_EMOJI: ':robot_face:'
      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          ref: ${{ steps.get_tag.outputs.TAG }}
          description: ${{ steps.get_tag.outputs.TAG }}
          environment: staging
      - uses: evolv-ai/github-actions/release@master
        name: Deploy the code
        with:
          stage-to-release: staging
          release-script: /scripts/myman.sh
      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
      - uses: meeDamian/github-release@2.0
        if: success()
        with:
          token: ${{ github.token }}
          tag: v${{ steps.get_tag.outputs.SEM_VER }}
          name: v${{ steps.get_tag.outputs.SEM_VER }}
          prerelease: true
          allow_override: true
      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
      - name: Slack Notification (Success)
        if: success()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: deploy-staging
          SLACK_TITLE: asset-manager deployment success
          SLACK_MESSAGE: 'Deployment of tag ${{ steps.get_tag.outputs.TAG }} to staging succeeded. https://github.com/evolv-ai/asset-manager/tree/${{ steps.get_tag.outputs.TAG }}'
          SLACK_COLOR: '#33cc33'
          SLACK_TITLE: Staging Deployment
          SLACK_USERNAME: deploy-bot
          SLACK_ICON_EMOJI: ':robot_face:'
      - name: Slack Notification (Failure)
        if: failure()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: deploy-staging
          SLACK_TITLE: asset-manager deployment failure
          SLACK_MESSAGE: 'Deployment of tag ${{ steps.get_tag.outputs.TAG }} to staging failed.  https://github.com/evolv-ai/asset-manager/tree/${{ steps.get_tag.outputs.TAG }}'
          SLACK_COLOR: '#ff0000'
          SLACK_TITLE: Staging Deployment
          SLACK_USERNAME: deploy-bot
          SLACK_ICON_EMOJI: ':robot_face:'
