on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    name: A job to release some code
    steps:
    - name: Checkout source code
      uses: actions/checkout@v1
    - name: Release step
      id: hello
      uses: evolv-ai/github-actions/release@master
      with:
        stage-to-release: 'staging'
        release-script: '/scripts/myman.sh'
